OPERANDS = {"~": 4, "&": 3, "||": 3, "=>": 1, "<=>": 1}
PROBABILITY_OF_HORN_QUERY_BEING_AN_EXPRESSION = 0.7
PROBABILITY_OF_QUERY_BEING_AN_EXPRESSION = 0.6
HORN_METHODS = ["FC", "BC", "TT"]
GENERAL_METHODS = ["TT", "DPLL", "Resolution"]
PROGRAM_PATH_1 = "./dist/main.exe"
PROGRAM_PATH_2 = "./dist/other.exe"
NUM_SYMBOLS_LOW = 4
NUM_SYMBOLS_HIGH = 6
NUMBER_OF_HORN_CLAUSES = 8
NUMBER_OF_GENERAL_CLAUSES = 4
NUMBER_OF_SYMBOLS_FIX = 3
DEPTH = 2
TEST_FILE_NAME = "./test.txt"
TEST_FOLDER_NAME = "./test/"
